export const SET_TEXT_FIELD_VALUE = "SET_TEXT_FIELD_VALUE" as const;
export const SET_NUMBER_FIELD_VALUE = "SET_NUMBER_FIELD_VALUE" as const;
export const UPDATE_FIELD = "GET_UPDATED_DATA" as const;
export const CREATE_RECORD_SUCCESS = "CREATE_RECORD_SUCCESS" as const;
export const CREATE_RECORD_FAILED = "CREATE_RECORD_FAILED" as const;